name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 79597749-5c07-485f-b3ae-1ac467d22b47
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
